// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/audit" | "/admin/policies" | "/admin/research" | "/admin/review" | "/apply" | "/flows/[id]" | "/flows/kebele-id" | "/flows/submit" | "/flows/trade-license" | "/flows/trade-license/step-1" | "/flows/trade-license/step-2" | "/flows/trade-license/step-3" | "/flows/trade-license/success" | "/flows/vital-events" | "/login" | "/queue" | "/services" | "/services/[id]" | "/test-admin" | "/test-offline" | "/track" | "/track/[id]" | "/vault" | "/vault/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/flows" | "/flows/[id]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/audit": {}
  "/admin/policies": {}
  "/admin/research": {}
  "/admin/review": {}
  "/apply": {}
  "/flows": {}
  "/flows/[id]": { "id": string; }
  "/flows/kebele-id": {}
  "/flows/submit": {}
  "/flows/trade-license": {}
  "/flows/trade-license/step-1": {}
  "/flows/trade-license/step-2": {}
  "/flows/trade-license/step-3": {}
  "/flows/trade-license/success": {}
  "/flows/vital-events": {}
  "/login": {}
  "/queue": {}
  "/services": {}
  "/services/[id]": { "id": string; }
  "/test-admin": {}
  "/test-offline": {}
  "/track": {}
  "/track/[id]": { "id": string; }
  "/vault": {}
  "/vault/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/flows": never
  "/flows/[id]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
