// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/policies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/policies">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/policies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/research">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/review">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/apply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply">> = Specific
  const handler = {} as typeof import("../../../src/app/apply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flows/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/flows/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flows/kebele-id/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows/kebele-id">> = Specific
  const handler = {} as typeof import("../../../src/app/flows/kebele-id/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flows/submit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows/submit">> = Specific
  const handler = {} as typeof import("../../../src/app/flows/submit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flows/trade-license/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows/trade-license">> = Specific
  const handler = {} as typeof import("../../../src/app/flows/trade-license/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flows/trade-license/step-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows/trade-license/step-1">> = Specific
  const handler = {} as typeof import("../../../src/app/flows/trade-license/step-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flows/trade-license/step-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows/trade-license/step-2">> = Specific
  const handler = {} as typeof import("../../../src/app/flows/trade-license/step-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flows/trade-license/step-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows/trade-license/step-3">> = Specific
  const handler = {} as typeof import("../../../src/app/flows/trade-license/step-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flows/trade-license/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows/trade-license/success">> = Specific
  const handler = {} as typeof import("../../../src/app/flows/trade-license/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flows/vital-events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows/vital-events">> = Specific
  const handler = {} as typeof import("../../../src/app/flows/vital-events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/queue">> = Specific
  const handler = {} as typeof import("../../../src/app/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/services/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/services/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../src/app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-admin">> = Specific
  const handler = {} as typeof import("../../../src/app/test-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-offline">> = Specific
  const handler = {} as typeof import("../../../src/app/test-offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/track/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/track/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/track/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/track/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/track">> = Specific
  const handler = {} as typeof import("../../../src/app/track/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/vault/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vault/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/vault/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/vault/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vault">> = Specific
  const handler = {} as typeof import("../../../src/app/vault/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flows/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/flows/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/flows/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flows/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/flows">> = Specific
  const handler = {} as typeof import("../../../src/app/flows/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
