openapi: 3.1.0
info:
  title: GAE RAG Agent API
  version: 1.0.0
  description: API for regulatory research (PRA) and guidance (RAG) services.

paths:
  /v1/research/policy-draft:
    post:
      summary: Start a new policy research job
      tags: [Research]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [query]
              properties:
                query:
                  type: string
                  example: "VAT registration for SMEs in Addis Ababa"
                jurisdiction:
                  type: string
                  default: "Federal"
      responses:
        '202':
          description: Research job accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    format: uuid

  /v1/research/drafts/{draftId}:
    get:
      summary: Retrieve a policy draft and its source bundle
      tags: [Research]
      parameters:
        - name: draftId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Policy draft details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyDraft'

  /v1/guidance/query:
    post:
      summary: Ask a natural language question about regulations
      tags: [Guidance]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [question]
              properties:
                question:
                  type: string
                  example: "How do I renew my trade license?"
                analysis_context:
                  type: object
                  description: Optional context from current document analysis
      responses:
        '200':
          description: Guidance response with citations
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string
                  citations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Citation'
                  confidence_score:
                    type: number
                  escalated_to_human:
                    type: boolean

components:
  schemas:
    PolicyDraft:
      type: object
      properties:
        id: { type: string, format: uuid }
        title: { type: string }
        jurisdiction: { type: string }
        content: { type: object }
        confidence_score: { type: number }
        status: { type: string, enum: [DRAFT, PENDING_REVIEW, APPROVED, REJECTED] }

    Citation:
      type: object
      properties:
        id: { type: string, format: uuid }
        claim_text: { type: string }
        document_id: { type: string }
        page_number: { type: integer }
        snippet: { type: string }
